### PR TITLE
Rename the metrics & labels to be consistent with Prometheus guidelines (or try to)

### PR DESCRIPTION
**Pull request by fedepaol**
This PR tries to make the labelling convention more near to Prometheus conventions.

Links:
https://prometheus.io/docs/practices/rules/
https://prometheus.io/docs/practices/naming/

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold
Still need to validate it

**Comment by fedepaol** [comment]
/hold cancel
validated it

**Comment by paulfantom** [comment]
LGTM :+1:

**Pull request merged**
