### PR TITLE
Expose the metrics over a https channel.

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold
needs validation

**Comment by SchSeba** [comment]
@fedepaol can you update the PR to integrate this project into the CNO and link between the PR's ?

**Comment by fedepaol** [comment]
> @fedepaol can you update the PR to integrate this project into the CNO and link between the PR's ?

What do you mean by "to integrate this project" ? I thought the update of CNO was done manually

**Pull request merged**
